/* @flow */
export const cssPrefix: string = 'daze-'
export const colorTypes: Array<string> = [
  'white',
  'black',
  'success',
  'success-light',
  'success-lighter',
  'success-dark',
  'success-darker',
  'complete',
  'complete-light',
  'complete-lighter',
  'complete-dark',
  'complete-darker',
  'primary',
  'primary-light',
  'primary-lighter',
  'primary-dark',
  'primary-darker',
  'warning',
  'warning-light',
  'warning-lighter',
  'warning-dark',
  'warning-darker',
  'danger',
  'danger-light',
  'danger-lighter',
  'danger-dark',
  'danger-darker',
  'info',
  'info-light',
  'info-lighter',
  'info-dark',
  'info-darker',
]
